
      
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% 

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% General Model settings

xbm = xb_generate_model(...
    'bathy',...
        {'x', Xqrs, 'y', Yqrs, 'z', zg,... %          %'xgrid', {'dxmin',dxmin,'dxmax',dxmax},... % ,'dxmax',dxmax        %'ygrid', {'dymin',dymin,'dymax',dymin},... % 'ygrid',         'area_type','range','area_size',[0.30 0.70] {'area_size',1000},...   'area_type','center','area_size',0.5     
        'rotate', alfa, ...
        'crop', false,...
        'world_coordinates',true},... %'finalise', {'n',4,'zmin', -20, 'z0', 0,'actions', {'lateral_extend' 'seaward_flatten', 'seaward_extend'},'zmin',-30}}
    'tide',... 
        {'time', tide_time, ... 
        'back', tide_back, ...
        'front', tide_front}, ... 
    'settings', ...
        {'outputformat',outputformat,... 
        'instat','jons_table',...
        'bcfile','jonswap.txt',...
        'structure',1,...
        'ne_layer','ne_layer',...
        'morfac', 10,...
        'morstart', 0, ...
        'CFL', 0.7,... % 'C', 45, 'zsinitfile', 'zsinit.dep',  ...
        'front', 'abs_2d', ...
        'back', 'abs_2d', ...
        'xori',xori,...
        'yori',yori,...
        'vardx',1,...
        'mpiboundary','x',...
        'thetamin', 15, ...
        'thetamax', 165, ...
        'dtheta',15,...
        'thetanaut', 1, ...
        'tstop', T, ...
        'tstart', 0,...
        'tintg', T/24,...
        'tintm', T/2,...
        'D50', .000434,...
        'epsi',-1,...              
        'facua',0.10,...
        'bedfriction', 'manning',...
        'meanvar',          {'zb', 'zs', 'H', 'ue', 've','thetamean'} ,...
        'globalvar',        {'zb', 'zs', 'H', 'ue', 've','sedero','hh','Svtot','Svtot'}},...
        'write', false,...
        'createwavegrid',false);  % 'npoints', {'265626.171 6815752.89'}, ...'npoints', {'265626.171 6815752.89'}, ... 'pointvar', {'zs'}, ...


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Clean Up Grid

    % Get grid
        xgrid                   = xs_get(xbm,'xfile.xfile');
        ygrid                   = xs_get(xbm,'yfile.yfile');
        zgrid                   = xs_get(xbm,'depfile.depfile');

    % Maximum and minimum values       
        id1 = find(zgrid > 5);
        for i = 1:length(id1)
            zgrid(id1(i)) = 5;
        end

        id2 = find(zgrid < -30);
        for i = 1:length(id2)
            zgrid(id2(i)) = -30;
        end
        
    % Straight boundaries

        [nx ny]                             = size(zgrid);
        roundnumber                         = 5;
        first                               = 1;
        second                              = roundnumber;
        third                               = nx-(roundnumber-1);
        four                             	= nx;
        five                                = ny - (roundnumber-1);
        six                                 = ny;
        zgrid([first:second],:)             = repmat(zgrid(second,:),[roundnumber,1]); 
        zgrid([(third:four)],:)             = repmat(zgrid((third),:),[roundnumber,1]);
        zgrid(:,[five:six])                 = repmat(zgrid(:,six),[1,roundnumber]);
        xbm                                 = xs_set(xbm, 'depfile.depfile', zgrid);




