    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% 

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% General Model settings

xbm = xb_generate_model(...
    'settings', ...
        {'outputformat','netcdf',... 
        'instat','jons_table',...
        'bcfile','jonswap.txt',...
        'struct',1,...
        'ne_layer','ne_layer.dep',...
        'morfac', 10,...
        'morstart', 0, ...
        'CFL', 0.7,... % 'C', 45, 'zsinitfile', 'zsinit.dep',  ...
        'front', 'abs_2d', ...
        'back', 'abs_2d', ...
        'right', 'neumann',...
        'left', 'neumann',...
        'gridform','delft3d',...
        'tidelen',7451,...
        'xyfile','xyfile.txt',...
        'vardx',1,...
        'nx',117,...
        'ny',192,...
        'mpiboundary','x',...
        'lateralwave','wavecrest',...
        'wavemodel','surfbeat',...
        'thetamin', 15, ...
        'thetamax', 165, ...
        'dtheta',15,...
        'thetanaut', 1, ...
        'tstop', duration_s, ...
        'tstart', 0,...
        'tintg', 360,...
        'tintm', duration_s,...
        'D50', .000434,...
        'epsi',-1,...              
        'facua',0.10,...
        'bedfriction', 'manning',...
        'globalvar',        {'zb', 'zs', 'H', 'ue', 've','sedero','hh','Svtot','Svtot'}},...
        'write', false,...
        'createwavegrid',false);  

    % Additional Parameters
        %         'xori',xori,...
        %         'yori',yori,...    
        %             'meanvar',          {'zb', 'zs', 'H', 'ue', 've','thetamean'} ,...
        % 'npoints', {'265626.171 6815752.89'}, ...'npoints', {'265626.171 6815752.89'}, ... 'pointvar', {'zs'}, ...




        
        
        
        
        
        
